http request method: POST

url : http://{your-cmdb-ip}:8080/webservices/rest.php

send body : {
  "body content type": "Form Urlencoded",
  "Specify Body": "Using Fields Below",
  "Body Parameters": [
    {
      "name": "version",
      "value": "1.3"
    },
    {
      "name": "auth_user",
      "value": "admin"
    },
    {
      "name": "auth_pwd",
      "value": "password"
    },
    {
      "name": "json_data",
      "value": 
      {
        "Operation": "core/get",
        "Class": "VirtualMachine",
        "Key": "SELECT VirtualMachine AS VM JOIN Hypervisor AS HV ON VM.virtualhost_id = HV.id JOIN Server AS S ON HV.server_id = S.id WHERE S.managementip = '{{ $('On form submission').item.json['IP Management Server']}}'",
        "Output_fields": "*"
      }
    }
  ]
}